services:
  - type: web
    name: eukexpress
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    pythonVersion: 3.11.9
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9